### ISSUE TITLE
Publish russound on pypi

### ISSUE THREAD

**Issue by andrey-git** [laf/russound#5]
Could you publish this package on Pypi, so it can be fetched without specifying the github URL?

home-assistant/home-assistant#7069

**Comment by laf** [comment]
Sure thing, any info on how to do that - I'm no Python guy :/

**Comment by andrey-git** [comment]
Here is unofficial guide: http://peterdowns.com/posts/first-time-with-pypi.html
Here is the official guide: https://packaging.python.org/distributing/

I followed the official guide for my package. The unofficial seems a little shorter (however didn't test it myself)

**Comment by laf** [comment]
https://pypi.python.org/pypi/russound/0.1.7

Hopefully that works.

**Comment by andrey-git** [comment]
Works fine, thanks!

**Comment by laf** [comment]
Ace :)
